name: Build GeoIP

on:
  schedule:
    - cron: '0 0 * * 0'  # каждое воскресенье в 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Clone geoip tool
        run: git clone https://github.com/v2fly/geoip.git

      - name: Download dependencies
        run: |
          cd geoip
          go mod download

      - name: Generate geoip.dat
        run: |
          cd geoip
          go run ./ -c ../config.json
          mv output/dat/geoip.dat ../geoip.dat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: geoip.dat
          path: geoip.dat

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest GeoIP
          body: Автоматически сгенерированный файл geoip.dat
          files: geoip.dat
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
