name: Build GeoIP

on:
  schedule:
    - cron: '0 0 * * 0'  # Каждое воскресенье в полночь
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download latest full geoip.dat
        run: |
          curl -L -o geoip.dat https://github.com/runetfreedom/russia-blocked-geoip/releases/latest/download/geoip.dat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: geoip.dat
          path: geoip.dat

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest GeoIP
          body: Полный geoip.dat из runetfreedom/russia-blocked-geoip
          files: geoip.dat
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
